@startuml
title 3. Добавление договора аренды

start

:Ввод данных:
помещение, арендатор,
даты, стоимость;

:Загрузить список занятых помещений;

:Вывод: список занятых помещений;

if (Помещение свободно?) then (Да)
    :Создать запись в БД;
    :Сохранить данные договора;
    :Вывод: «Договор успешно добавлен»;
else (Нет)
    :Вывод: «Помещение занято»;
endif

stop

@enduml