@startuml
title 1

start
:Ввод: заявка на возврат помещения;
:Проверить договор аренды;
:Осмотреть помещение;
:Зафиксировать состояние помещения;

if (Помещение повреждено?) then (Да)
    :Составить акт о повреждениях;
    :Уведомить техслужбу;
    :Рассчитать стоимость ремонта;
else (Нет)
    :Принять помещение без замечаний;
endif

:Принять ключи;
:Проверить оплату;

if (Оплата произведена?) then (Да)
    :Закрыть договор;
    :Освободить помещение в реестре;
else (Нет)
    :Уведомить администратора о задолженности;
endif

stop
@enduml