@startuml
title 1. Процесс выдачи помещения

start

:Ввод: запрос на выдачу помещения;

:Загрузить данные о состоянии помещения;

:Вывод: данные о состоянии помещения;

if (Помещение в рабочем состоянии?) then (Да)
    :Подготовить ключи и документы;
    :Выдать ключи;
    :Использование помещения;
    :Возврат ключей;
    :Закрыть договор;
else (Нет)
    :Уведомить техслужбу;
endif

stop

@enduml